IV Objetivo 2 [IV-21-22]
sorozcov/proyecto-iv-ugr pull request #10
Opened 2021-11-15 12:12 UTC by gomares

Entrega del objetivo 2, incluyendo los siguientes cambios:

- Actualización de .gitignore para adaptarlo a Python.
- Extendemos la documentación para el nuevo objetivo.
- Actualización del README.md.
- Se incluye iv.yaml.
- Se incluye  [HU-P1] El problema de representar la clase Partido #9 .
- Se implementa la clase Partido.

2021-11-15 13:08 UTC, sorozcov approved these changes
Revisado, la implementación base de la clase para la representación de un partido.

2021-11-15 13:12 UTC, gomares commented
Listo para revisión @JJ

2021-11-21 18:50 UTC, JJ requested changes
Por favor, seguir la metodología que se especifica en el guión, y pasar la lista de comprobación antes de la siguiente revisión.

2021-11-21 18:50 UTC, JJ commented on code/partido.py
> +    id : str
¿Qué HU pide esto? ¿Por qué lo pide la lógica de negocio?

2021-11-21 18:50 UTC, JJ commented on code/partido.py
> +        self.fecha = fecha
¿Has mirado lo que dice #5? ¿Las cosas sobre las que se puede apostar? ¿De qué forma están reflejadas aquí?

2021-11-25 19:49 UTC, gomares commented
Ya está todo por mi parte, revísalo y si quieres lo mandamos a revisión. Creo haber cubierto toda la historia de usuario #5 . @sorozcov .

2021-11-26 08:27 UTC, gomares commented
Listo para revisión @JJ. Ya me aprobó los cambios Silvio!

2021-11-26 09:28 UTC, JJ approved these changes
:+1: Pero seguramente hará falta algo de trabajo por parte de @sorozcov sobre todo a la hora de concretar el objetivo 4.

2021-11-26 09:28 UTC, JJ commented on code/apuesta.py
> +    Resultado = auto()
Yo habría dejado el tipo de apuesta abierto, porque esto te limita, pero vale.

2021-11-30 16:23 UTC, merged