Objetivo 3
sorozcov/proyecto-iv-ugr pull request #15
Opened 2021-12-01 09:57 UTC by sorozcov

Se ha trabajado en:

- #12 
- #13 
- #14

2021-12-01 10:31 UTC, sorozcov commented
Lo siento el último commit ha sido una mala práctica porque no hice fetch antes realizar un nuevo commit (Lo cual mencionaste mucho en clase). No volverá a suceder.
Listo para revisión @JJ

2021-12-07 16:41 UTC, JJ requested changes
En vez de seguir al pie de la letra lo que se pide, podíais tratar de entender lo que hacéis y por qué. Por ejemplo, [en este milestone](https://github.com/sorozcov/proyecto-iv-ugr/milestone/5) tendrías que haber incluido este sistema de automatización en vez de simplemente añadirlo para que pasara el test.

2021-12-07 16:41 UTC, JJ commented on README.md
> +Primero instalamos las dependencias del proyecto
¿No hace falta instalar invoke?

2021-12-07 16:41 UTC, JJ commented on README.md
> +``poetry install``
¿Tampoco hace falta instalar poetry?
Además, es `installdeps`

2021-12-07 16:41 UTC, JJ commented on docs/objetivo3.md
> +
Nunca he pedido que me comuniquéis vuestra decisión. Lo que quiero es que me mostréis que sabéis buscar entre las herramientas existentes y que tenéis una serie de criterios a priori para seleccionar la herramienta más adecuada para vuestro proyecto.

2021-12-07 16:41 UTC, JJ commented on docs/objetivo3.md
> +Se debe utilizar poetry cli de la siguiente forma, obtenido de la documentación de Poetry:
¿Y qué aportas copiándolo aquí?

2021-12-07 16:41 UTC, JJ commented on docs/objetivo3.md
> +-   ``poetry shell``: The first time this command is run in your project directory, Poetry creates a Python virtual environment which will forever be associated with this project. Instead of creating
Agh, ¿por qué? ¿Qué se aporta con esto a la consecución del objetivo? ¿Que sabes copiar y pegar?

2021-12-07 16:41 UTC, JJ commented on tasks.py
> +    run("pyflakes code")
¿Por qué usas pyflakes como un montón de compañeros? ¿Es eso lo que se pide?

2021-12-07 17:30 UTC, sorozcov commented on docs/objetivo3.md
> +-   ``poetry shell``: The first time this command is run in your project directory, Poetry creates a Python virtual environment which will forever be associated with this project. Instead of creating
Se han colocado únicamente los comandos necesarios para el proyecto con la explicación propia sobre porque son necesarios y el proceso a seguir para la instalación.

2021-12-07 17:31 UTC, sorozcov commented on docs/objetivo3.md
> +Se debe utilizar poetry cli de la siguiente forma, obtenido de la documentación de Poetry:
Se ha modificado la documentación para que los comandos importantes puedan consultarse de forma que en un futuro cualquiera tenga los pasos a seguir para instalar el proyecto en su ordenador.

2021-12-07 17:31 UTC, sorozcov commented on README.md
> +Primero instalamos las dependencias del proyecto
Se ha actualizado la documentación.

2021-12-07 17:31 UTC, sorozcov commented on README.md
> +``poetry install``
Se ha actualizado la documentación.

2021-12-07 17:38 UTC, sorozcov commented
> En vez de seguir al pie de la letra lo que se pide, podíais tratar de entender lo que hacéis y por qué. Por ejemplo, [en este milestone](https://github.com/sorozcov/proyecto-iv-ugr/milestone/5) tendrías que haber incluido este sistema de automatización en vez de simplemente añadirlo para que pasara el test.

Se ha actualizado el milestone para que tome en consideración el sistema de automatización.

2021-12-07 18:25 UTC, sorozcov commented on tasks.py
> +    run("pyflakes code")
Se ha utilizado pyflakes porque es ligero y rápido en comparación de otros comprobadores de código para encontrar violaciones comunes en el código.Sin embargo, he visto que no comprueba la sintáxis por completo ya que no compila los archivos y por tanto, puede fallar en detectar ciertos errores. Por ello, se ha agregado una línea que compile todos los archivos del código que al mismo tiempo daría error si hubiese un error de sintáxis en los archivos.

2021-12-07 18:26 UTC, sorozcov commented on tasks.py
> +    run("pyflakes code")
Pyflakes analiza los programas para detectar errores en los mismos tantos de imports incorrectos como de sintáxis que es lo que se pide. Es ligero y más rápido que otros analizadores, así como muy sencillo de instalar. A pesar de no ser tan configurable como Pylint es suficiente para satisfacer la tarea de verificar errores de sintáxis en el código.

2021-12-07 18:32 UTC, sorozcov commented
Listo para revisión @JJ

2021-12-07 18:50 UTC, JJ requested changes
Por favor, la próxima vez realmente revisa todo lo que se ha comentado, especialmente lo que tenga más importancia para superar el objetivo.

2021-12-07 18:50 UTC, JJ commented on pyproject.toml
> +pyflakes = "^2.4.0"
¿Por qué usas pyflakes... como todo el mundo? (Igual de mal, también)

2021-12-07 18:50 UTC, JJ commented on tasks.py
> +    run("pyflakes code")
Ping

2021-12-07 18:50 UTC, JJ commented on tasks.py
> +    run("python -m compileall code")
No entiendo. ¿Por qué haces las dos cosas?

2021-12-07 18:50 UTC, JJ commented on tasks.py
> +    print("Test de versión ejecutado correctamente")
Entonces, ¿para qué sirve c?

2021-12-07 18:50 UTC, JJ commented on README.md
> +``pip install poetry``
¿Entonces poetry no sabe instalar invoke?
Por favor, intentad entender lo que hacéis y por qué lo hacéis.

2021-12-07 18:50 UTC, JJ commented on docs/objetivo3.md
> +
Os agradecería que cuando lo pongáis para revisión realmente hagáis caso de los comentarios que se os hacen.

2021-12-07 18:50 UTC, JJ commented on docs/objetivo3.md
> +- ``poetry add [package-name]``: Este es el comando a correr siempre que deseemos agregar una dependencia al proyecto.
Insisto, ¿para qué sirve el manual de poetry? ¿Qué aporta para que yo entienda que has superado el objetivo?

2021-12-07 18:50 UTC, JJ commented on tests/test_version.py
> +__version__ = '0.4.0'
No sé para qué sirve esto ni por qué lo has puesto. Ni testea la lógica de negocio, ni sirve para nada.

2021-12-07 19:17 UTC, sorozcov commented on pyproject.toml
> +pyflakes = "^2.4.0"
Estoy utilizando pyflakes porque a pesar de un comprobador estático de código y que no compila los archivos, puede detectar otro tipo de errores como imports no usados que mantienen la calidad del código.

2021-12-07 19:17 UTC, sorozcov commented on tasks.py
> +    run("python -m compileall code")
Utilizo los 2 porque pyflakes realiza una comprobación estática del código que revisa errores para mantener la calidad del código y el compileall permite revisar que toda la sintáxis del código sea correcta compilando cada archivo si ha sufrido algún cambio.

2021-12-07 19:22 UTC, sorozcov commented on tests/test_version.py
> +__version__ = '0.4.0'
Si, fue un test de prueba que no tiene sentido. Lo he eliminado.

2021-12-07 19:22 UTC, JJ commented on pyproject.toml
> +pyflakes = "^2.4.0"
No se pide eso, no forma parte del producto mínimamente viable.

2021-12-07 19:23 UTC, JJ commented on tasks.py
> +    run("python -m compileall code")
Una vez más, no forma parte del producto mínimamente viable. No he pedido que comprobéis estáticamente el código, ni forma parte del objetivo.

2021-12-07 19:30 UTC, sorozcov commented on README.md
> +``pip install poetry``
Se ha actualizado la documentación para que se realicé de forma correcta.

2021-12-07 19:30 UTC, sorozcov commented on docs/objetivo3.md
> +- ``poetry add [package-name]``: Este es el comando a correr siempre que deseemos agregar una dependencia al proyecto.
Se ha eliminado ya que por el momento no aporta al proyecto y es simplemente utilizado por el gestor de tareas.

2021-12-07 19:40 UTC, sorozcov commented
Listo para revisión @JJ

2021-12-07 19:49 UTC, sorozcov commented on tasks.py
> +    run("python -m compileall code")
Hice unos commits y hasta ahora vi este comentario. Así que ahora haré otro commit para realizar dicho cambio.

2021-12-07 19:56 UTC, sorozcov commented
Listo para revision @JJ

2021-12-08 12:14 UTC, JJ approved these changes
Lo esencial de este objetivo es que aprendas a elegir herramientas y a justificarlas. No lo has hecho, pero tampoco creo que lo hagas mucho mejor. Vas a seguir eligiendo `invoke`, y buscando alguna cosa más para justificar por qué lo has hecho que nada tengan que ver con seguir un proceso preciso para tomar decisiones sobre herramientas, porque ya es demasiado tarde para eso.
Sin embargo, esto es algo que sí tienes que hacer en prácticamente todos los objetivos. Por favor, síguelo a partir de ahora.

2021-12-08 12:14 UTC, JJ commented on docs/objetivo3.md
> +-Invoke es una herramienta de gestión de tareas y librerías que es ligera, muy bien documentada y fácil/simple de utilizar.
¿Cuales son los criterios entonces? ¿doit es pesada, mal documentada y difícil de utilizar?

2021-12-08 12:14 UTC, JJ commented on docs/objetivo3.md
> +- Es la librería más sotisficada el día de hoy para manejar dependencias en python.
typo. No es la más sofisticada, es la que sigue el estándar. Por favor, informaros también un poco antes de escribir.

2021-12-10 13:31 UTC, merged