Objetivo 4
sorozcov/proyecto-iv-ugr pull request #22
Opened 2021-12-11 16:12 UTC by sorozcov

Se trabaja en el Objetivo 4 con los siguientes issues:

- #18 
- #19 
- #20 
- #21

2021-12-11 16:15 UTC, sorozcov commented
Listo para revisión @JJ

2021-12-11 16:26 UTC, sorozcov commented
> Listo para revisión @JJ

También tengo duda que no me ha aparecido en el Test las personas aleatorias para que también pudiesen revisar mi objetivo. Me imagino que aún no está programa, pero me queda duda si se me ha pasado. Gracias.

2021-12-12 09:29 UTC, JJ approved these changes
El test debe ser parte integral para comprobar la viabilidad de un producto mínimo, no algo "adicional". Por otro lado, no parece que el que el código esté en `code` siga las mejores prácticas en Python. Tampoco debes colocar los CSV en ese mismo directorio, y más si son sólo para test.
Lo fundamental en este objetivo (y en todos) es que justifiques los criterios que has elegido para elegir las herramientas, y no que comuniques la decisión.
También que testees la lógica de negocio, y no que pongas funciones absurdas que nada tienen que ver con tu aplicación para testear.

2021-12-12 09:29 UTC, JJ commented on code/historial_partidos.py
> +        ultimos_partidos_equipo_2 = list(map((lambda partido: partido if equipos[1] in partido.equipos else None), self.partidos))
Esto puede ser simplemente un bucle.

2021-12-12 09:29 UTC, JJ commented on code/historial_partidos_exceptions.py
> +class NotInt(Exception):
???

2021-12-12 09:29 UTC, JJ commented on code/historial_partidos.py
> +    def revisar_cantidad_mayor_a_0(self, cantidad):
Esto es un simple if. ¿Para que'sirve?

2021-12-12 09:29 UTC, JJ commented on code/historial_partidos.py
> +    def revisar_2_equipos(self,equipos):
¿En serio?

2021-12-12 09:29 UTC, JJ commented on code/historial_partidos.py
> +    def leer_datos(self, ficheros=['spain2007-2018.csv']):
¿Por qué no es parte del constructor?
En todo caso, la clase no debería leer los datos, porque estos pueden estar almacenados de muchas formas diferentes. Debería recibir los datos en el constructor.

2021-12-12 12:50 UTC, sorozcov commented on code/historial_partidos.py
> +        ultimos_partidos_equipo_2 = list(map((lambda partido: partido if equipos[1] in partido.equipos else None), self.partidos))
Listo, arreglado para que sea un solo bucle.

2021-12-12 12:51 UTC, sorozcov commented on code/historial_partidos.py
> +    def revisar_cantidad_mayor_a_0(self, cantidad):
Sirve para verificar que solo se solicite información de 2 equipos ya que de lo contrario podría fallar la generación de partidos.

2021-12-12 12:56 UTC, sorozcov commented on code/historial_partidos.py
> +    def revisar_2_equipos(self,equipos):
Esto sirve para verificar que solo solicite información sobre equpos válidos.

2021-12-12 12:56 UTC, sorozcov commented on code/historial_partidos.py
> +    def leer_datos(self, ficheros=['spain2007-2018.csv']):
Tienes razón, he cambiado esta parte para leer los datos desde el constructor.

2021-12-12 13:12 UTC, sorozcov commented
He realizado cambios sobre lo mencionado @JJ. Listo para revisión.

2021-12-12 16:53 UTC, JJ commented on code/historial_partidos.py
> +    def revisar_2_equipos(self,equipos):
No, comprueba que una lista tiene dos elementos. ¿Necesitas una función para eso? ¿Y una excepción? ¿O tomar los dos primeros equipos y ya está? ¿O poner una función con dos argumentos, ambos obligatorios? De verdad que debéis darle una vuelta al código que escribís para hacer algo. Siempre hay muchas opciones, pero la que has escogido no es la mejor.

2021-12-12 17:02 UTC, JJ requested changes
Aparte de lo comentado, no tenog muy claro que estés realmente testeando la lógica de negocio, más allá de ordenar conjuntos de partidos.

2021-12-12 17:02 UTC, JJ commented on docs/objetivo4.md
> +Como librería de assertions se ha decidido utilizar ``assertpy`` ya que tiene un API muy bueno y fácil para realizar assertions de varios tipos junto con una documentación fácil y sencilla de utiliza
No, estás usando pytest como librería de aserciones porque assertpy no tiene una aserción que compruebe si se ha levantado una excepción.
En todo caso, no os pido que comuniquéis vuestra decisión, sino que examinéis las opciones. Lo he explicado repetidamente en clase,  está en los errores frecuentes.

2021-12-12 17:02 UTC, JJ commented on docs/objetivo4.md
> +- Documentación de assertpy
Esto no es un criterio  a priori, sino una justificación.

2021-12-12 17:02 UTC, JJ commented on docs/objetivo4.md
> +- Amplia funcionalidad de assertpy para simplificar el uso de asserts sin tener que programar mucho más.
... excepto excepciones.

2021-12-12 17:02 UTC, JJ commented on docs/objetivo4.md
> +- Se reduce código boilerplate y se centra en funciones legibles y sencillas que testean las funcionalidades.
Ninguna de estas razones es ni anterior a la decisión, ni específica del proyecto, ni siquiera específica de esta biblioteca con respecto a otras. Que, por cierto, ¿cuales hay?

2021-12-14 10:41 UTC, sorozcov commented on code/historial_partidos.py
> +    def revisar_2_equipos(self,equipos):
Claro, gracias.

2021-12-14 10:43 UTC, sorozcov commented on code/historial_partidos.py
> +        ultimos_partidos = list(filter((lambda partido: partido!=None),ultimos_partidos))
Okay, gracias.

2021-12-14 10:43 UTC, sorozcov commented on code/historial_partidos.py
> +        ultimos_partidos_equipo_1 = list(filter((lambda partido: partido!=None),ultimos_partidos_equipo_1))
Okay, gracias.

2021-12-14 11:03 UTC, sorozcov commented on code/historial_partidos.py
> +        return len(equipos)==2
Se ha eliminado dicha función cambiando los parámetros como me sugeriste en la parte de arriba.

2021-12-14 11:15 UTC, sorozcov commented on docs/objetivo4.md
> +- Amplia funcionalidad de assertpy para simplificar el uso de asserts sin tener que programar mucho más.
También tiene un api para capturar excepciones cuando se invocan funciones que ahora estoy utilizando. Había entendido mal la documentación ya que recomienda utilizar el test runner para capturar excepciones pero no cuando estamos invocando una función.

2021-12-14 12:25 UTC, sorozcov commented
Se han modificado con las sugerencias @JJ. El ordenamiento de los partidos es parte de la lógica de negocio tanto para mostrar estos resultados a los usuarios como verificar que el algoritmo puede recibir los datos correctos. También he avanzado en la lógica de negocio en una apuesta para calcular las posibles ganancias. Si se desea avanzar más en la lógica de negocios, es el algoritmo de predicción que es el siguiente paso del proyecto.

2021-12-14 12:25 UTC, sorozcov commented
Listo para revisión @JJ

2021-12-16 11:26 UTC, JJ requested changes
Te he abierto un issue #24 , que sería creo yo lo mínimo que habría que implementar como lógica de negocio en este objetivo. También hay una serie de problemas puntuales que deberías tratar de resolver, sobre todo en cuando a la elección de herramientas.

2021-12-16 11:26 UTC, JJ commented on README.md
> +La librería de tests que se está utilizando es pytest.
No es una librería, es un framework (con varias librerías) junto con un test runner.

2021-12-16 11:26 UTC, JJ commented on code/apuesta.py
> +                raise BetPlaceNotFound()
En todas las excepciones debes decir qué es lo que ha causado la excepción. En este cso, el lugar. También arriba, en el tipo de apuesta.

2021-12-16 11:26 UTC, JJ commented on code/apuesta.py
>          dinero_apostado : float
¿Estás mezclando el dinero apostado por una persona con la apuesta en sí? ¿No serán dos cosas diferentes, la apuesta (que será inmutable e igual para todos los que apuesten) y una apuesta de una persona, que tendrá que estar asociada a una persona determinada? ¿Cómo sabes quién ha hecho la apuesta?

2021-12-16 11:26 UTC, JJ commented on code/apuesta.py
> +            Método para apostar
En vez de un método, ¿no sería mejor que cada apuesta fuera un objeto valor diferente, con características propias? ¿Ves lo que ocurre si no se plantea claramente el problema y se hace el código para resolverlo?

2021-12-16 11:26 UTC, JJ commented on code/apuesta.py
> +        return dinero_apostado*self.odds
Ya está claro que el dinero apostado tiene que ser un objeto aparte. Pero si no lo fuera, ¿no es dinero_apostado un atributo? ¿Por qué tienes que pasárselo como un argumento? Una vez más, debes establecer muy claramente cuál es el problema que pretendes resolver.

2021-12-16 11:26 UTC, JJ commented on code/historial_partidos.py
> +    def leer_datos(self, ficheros=['spain2007-2018.csv']):
El constructor no debería de leer también los datos. El constructor construye, no lee ficheros. Debe recibir los datos necesarios para trabajar.

2021-12-16 11:26 UTC, JJ commented on code/historial_partidos.py
> +                    apuestas= [Apuesta(Tipo_apuesta.Ganador,'H',row['B365H'], Lugar_apuesta.B365),
Tu lógica de negocio debería ser independiente del formato en el que estén los datos. Por eso se hace la separación de funciones, y deberías tener un objeto que encapsulara todos estos datos que quieres obtener y que los obtenda de diferentes formas. Estás mezclando los dos objetos, los que tienen los datos y los que lo procesan, y eso no es una buena idea.

2021-12-16 11:26 UTC, JJ commented on code/historial_partidos.py
> +            self.generar_equipos()
El fichero se llama "leer_datos" y aquí genera equipos. Aparte de usar características específicas del fichero, como el significado de ciertas filas. No entiendo tampoco cómo generas apuestas sobre la base de partidos que ya han sucedido. ¿No estás confundiendo resultados con apuestas? ¿Y cómo vas a apostar dinero sobre resultados que ya han sucedido? No entiendo muy bien qué haces aquí, la verdad (aparte de las muchas cosas que hace)

2021-12-16 11:26 UTC, JJ commented on code/apuesta.py
>  class Apuesta:
Volviendo atrás, estás usando esto para almacenar resultados y también para crear apuestas a futuro. Una apuesta no puede tener un resultado esperado. Te he dicho más abajo que esto haría dos cosas, pero en realidad es que haría tres: resultados pasados, posibles cosas sobre las que apostar, apuestas de una persona. Tendrías que haber planteado el problema claramente en uno (o varios) issues y resolverlo adecuadamente con código.

2021-12-16 11:26 UTC, JJ commented on tests/test_historial_partidos.py
> +def test_apuesta_hipotetica():
No hay ningún test (ni, aparentemente, implementación) de la lógica de negocio.

2021-12-22 17:37 UTC, sorozcov commented
Hola @JJ. Lo siento que hasta ahora lo envío para revisión, desde el día viernes he pasado con Covid y tuve varios síntomas en estos días especialmente estar agotado. Si aún pudieses revisar el día de hoy te lo agradecería, sino está bien lo seguiré mejorando para la fecha del examen. Gracias.

2021-12-22 17:38 UTC, sorozcov commented
Listo para revisión @JJ

2021-12-22 17:39 UTC, JJ requested changes
Repetidamente hemos dicho que tenéis que testear vuestra propia lógica de negocio sin usar ningun biblioteca externa, desde el objetivo 0. Por favor hazlo así. Y que te mejores.

2021-12-22 17:42 UTC, sorozcov commented
> Repetidamente hemos dicho que tenéis que testear vuestra propia lógica de negocio sin usar ningun biblioteca externa, desde el objetivo 0. Por favor hazlo así. Y que te mejores.

¿Cuál biblioteca externa? Es decir, no puedo utilizar numpy para algunos cálculos? No se usa en el testing.

2021-12-22 18:30 UTC, JJ commented
> > Repetidamente hemos dicho que tenéis que testear vuestra propia lógica de negocio sin usar ningun biblioteca externa, desde el objetivo 0. Por favor hazlo así. Y que te mejores.
> 
> ¿Cuál biblioteca externa? Es decir, no puedo utilizar numpy para algunos cálculos? No se usa en el testing.

No, no puedes. Todo el código que tengas en este objetivo tiene que ser tuyo. Ninguna biblioteca externa.

2021-12-22 18:33 UTC, JJ requested changes
Realmente no estás usando numpy para la lógica de negocio, pero aún así, esas funciones deberías escribirlas tú, porque se trata de que testeéis vuestro propio código. En todo caso, hay una serie de objeciones que te hice la semana pasada que no has tenido en cuenta.

2021-12-22 18:33 UTC, JJ commented on code/apuesta.py
>          dinero_apostado : float
Tampoco has contestado a esto que te comenté.

2021-12-22 18:33 UTC, JJ commented on tests/test_prediccion.py
> +import numpy as np
Esto no lo usas.

2021-12-22 22:58 UTC, sorozcov commented
> Realmente no estás usando numpy para la lógica de negocio, pero aún así, esas funciones deberías escribirlas tú, porque se trata de que testeéis vuestro propio código. En todo caso, hay una serie de objeciones que te hice la semana pasada que no has tenido en cuenta.

Claro, lo estaré revisando más a fondo entonces para que luego lo revises. Gracias.

2022-01-03 01:00 UTC, sorozcov commented on code/historial_partidos.py
> +                    apuestas= [Apuesta(Tipo_apuesta.Ganador,'H',row['B365H'], Lugar_apuesta.B365),
Esto se ha corregido.

2022-01-03 01:00 UTC, sorozcov commented on code/historial_partidos.py
> +            self.generar_equipos()
Esto se ha corregido.

2022-01-03 01:09 UTC, sorozcov commented on code/apuesta.py
>  class Apuesta:
Se han planteado los issues para que la clase apuesta.py por el momento solo se encargue sobre las posibles cosas sobre que apostar como una apuesta inmutable para todas las personas.

2022-01-03 01:10 UTC, sorozcov commented on code/apuesta.py
> +        return dinero_apostado*self.odds
Esto se ha corregido.

2022-01-03 01:11 UTC, sorozcov commented on code/apuesta.py
>          dinero_apostado : float
Esto se ha corregido.

2022-01-03 01:15 UTC, sorozcov commented on code/apuesta.py
> +            Método para apostar
Se ha corregido también creando una clase específica con sus características propias en el issue #25

2022-01-03 01:15 UTC, sorozcov commented on code/apuesta.py
> +                raise BetPlaceNotFound()
Se ha realizado la corrección.

2022-01-03 01:16 UTC, sorozcov commented on tests/test_historial_partidos.py
> +def test_apuesta_hipotetica():
Se ha implementado lógica de negocio para la predicción de un resultado #24

2022-01-03 01:18 UTC, sorozcov commented
Hola @JJ. He realizado correcciones para esta entrega. Como esta entrega la había dejado a medias antes del fin de teoría, quería saber como procedía para la revisión o asignación. Muchas gracias.

2022-01-03 19:57 UTC, JJ commented
> Hola @JJ. He realizado correcciones para esta entrega. Como esta entrega la había dejado a medias antes del fin de teoría, quería saber como procedía para la revisión o asignación. Muchas gracias.

Si no se hace asignación a nadie, no la vas a hacer ahora. Deberías haberla corregido en su momento. Ahora me temo que lo que salga de la corrección será definitivo.

2022-01-03 20:04 UTC, JJ requested changes
Lo siento, no has hecho la mayoría de los cambios que se te pidió, así que no has superado este objetivo.

2022-01-03 20:04 UTC, JJ commented on code/historial_partidos.py
> +                raise EquipoSolicitadoNoEstaEnPrimeraDivision("Equipo solicitado no se encuentra en primera división.")
REdundante.

2022-01-03 20:04 UTC, JJ commented on code/historial_partidos.py
> +    def revisar_cantidad_mayor_a_0(self, cantidad):
No se ha contestado.

2022-01-03 20:04 UTC, JJ commented on code/historial_partidos_exceptions.py
> +class NotInt(Exception):
Tampoco se ha contestado.

2022-01-03 20:04 UTC, JJ commented on docs/objetivo4.md
> +Como librería de assertions se ha decidido utilizar ``assertpy`` ya que tiene un API muy bueno y fácil para realizar assertions de varios tipos junto con una documentación fácil y sencilla de utiliza
Tampoco has contestado a esto.

2022-01-03 20:11 UTC, sorozcov commented
@JJ pero si si trabajé en los cambios, en objetivo4.md explico las decisiones tomadas y en issue #25 abordo los problemas sobre las apuestas que mencionaste. De igual forma, avancé la lógica de negocio del issue #24

2022-01-03 20:12 UTC, JJ commented
> @JJ pero si si trabajé en los cambios, en objetivo4.md explico las decisiones tomadas y en issue #25 abordo los problemas sobre las apuestas que mencionaste. De igual forma, avancé la lógica de negocio del issue #24

Ese era sólo uno de los problemas señalados. El resto también son importantes. De la mayoría de los comentarios, te has centrado en ese.

2022-01-03 20:19 UTC, sorozcov commented
> > @JJ pero si si trabajé en los cambios, en objetivo4.md explico las decisiones tomadas y en issue #25 abordo los problemas sobre las apuestas que mencionaste. De igual forma, avancé la lógica de negocio del issue #24
> 
> Ese era sólo uno de los problemas señalados. El resto también son importantes. De la mayoría de los comentarios, te has centrado en ese.


Pero todos los problemas que has señalado fueron trabajados en cada uno de los avances. El commit #84087c0 por ejemplo trabajo en la necesidad de revisar 2 equipos, cambiando los parámetros para generar un historial. La elección de las librerías fue justificada y usada correctamente testeando la lógica de negocio que era lo que solicitaba el objetivo.

2022-01-03 20:59 UTC, JJ commented
No, no lo fueron y en los comentarios en los que no lo hiciste te lo he
vuelto a recordar. Hay comentarios sobre los que no hiciste nada que
provienen de la primera revisión, hace 18 días. Si ni siquiera te das
cuenta de qué comentarios son los que no has comprobado, más razón todavía
para no pasar este objetivo. Puedes continuar con el siguiente, si lo
deseas.

2022-01-03 21:16 UTC, sorozcov commented on code/historial_partidos.py
> +    def revisar_2_equipos(self,equipos):
> No, no lo fueron y en los comentarios en los que no lo hiciste te lo he vuelto a recordar. Hay comentarios sobre los que no hiciste nada que provienen de la primera revisión, hace 18 días. Si ni siquiera te das cuenta de qué comentarios son los que no has comprobado, más razón todavía para no pasar este objetivo. Puedes continuar con el siguiente, si lo deseas.

Okay, seguiré con el siguiente objetivo. Pero de igual forma siento que he revisado los comentarios y los pasos a seguir en este objetivo, y si se corriegieron los aspectos que fueron comentados así como que había cumplido con lo solicitado. No todas las respuestas fueron en comentarios, sino también en los commits y en el trabajo realizado.

2022-01-03 21:19 UTC, sorozcov commented
> No, no lo fueron y en los comentarios en los que no lo hiciste te lo he vuelto a recordar. Hay comentarios sobre los que no hiciste nada que provienen de la primera revisión, hace 18 días. Si ni siquiera te das cuenta de qué comentarios son los que no has comprobado, más razón todavía para no pasar este objetivo. Puedes continuar con el siguiente, si lo deseas.

Okay, seguiré con el siguiente objetivo. Pero de igual forma siento que he revisado los comentarios y los pasos a seguir en este objetivo, y si se corriegieron los aspectos que fueron comentados así como que había cumplido con lo solicitado. No todas las respuestas fueron en comentarios, sino también en los commits y en el trabajo realizado. Si se pudiera volver a reconsiderar, mostrando que cumple con la mayoría de aspectos que solicita el objetivo.

2022-01-03 21:22 UTC, sorozcov commented
> > No, no lo fueron y en los comentarios en los que no lo hiciste te lo he vuelto a recordar. Hay comentarios sobre los que no hiciste nada que provienen de la primera revisión, hace 18 días. Si ni siquiera te das cuenta de qué comentarios son los que no has comprobado, más razón todavía para no pasar este objetivo. Puedes continuar con el siguiente, si lo deseas.
> 
> Okay, seguiré con el siguiente objetivo. Pero de igual forma siento que he revisado los comentarios y los pasos a seguir en este objetivo, y si se corriegieron los aspectos que fueron comentados así como que había cumplido con lo solicitado. No todas las respuestas fueron en comentarios, sino también en los commits y en el trabajo realizado. Si se pudiera volver a reconsiderar, mostrando que cumple con la mayoría de aspectos que solicita el objetivo.

Y también que el objetivo es evaluado sobre lo siguiente : 
* [ x]  ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [ ]  ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [ x]  ¿Ese issue está asignado a un milestone?
* [ x]  ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [x ]  ¿El PR, que también es un issue, está asignado al mismo milestone?

Consecución del objetivo#
Se consigue si se han configurado correctamente las herramientas de construcción y justificado mínimamente su elección en un documento aparte.

2022-01-05 13:05 UTC, sorozcov commented on docs/objetivo4.md
> +Como librería de assertions se ha decidido utilizar ``assertpy`` ya que tiene un API muy bueno y fácil para realizar assertions de varios tipos junto con una documentación fácil y sencilla de utiliza
Esto se ha contestado con la actualización de Objetivo4.md en commit #620ab1f

2022-01-05 18:19 UTC, merged

2022-01-28 08:06 UTC, sorozcov commented on code/historial_partidos_exceptions.py
> +class NotInt(Exception):
Esto se ha eliminado ya que finalmente lo vi innecesario cuando solo era una condicional if.

2022-01-28 08:06 UTC, sorozcov commented on code/historial_partidos.py
> +    def revisar_cantidad_mayor_a_0(self, cantidad):
Esto se ha eliminado ya que finalmente lo vi innecesario cuando solo era una condicional if.

2022-01-28 08:07 UTC, sorozcov commented on code/historial_partidos.py
> +    def leer_datos(self, ficheros=['spain2007-2018.csv']):
Se ha cambiado para que el constructor como bien dices solo trabaje con recibir ya los datos.

2022-01-28 08:09 UTC, sorozcov commented on code/historial_partidos.py
> +    def revisar_2_equipos(self,equipos):
Se ha cambiado a recibir 2 parámetros equipo1 y equipo2 obligatorias, en lugar de necesitar una revisión para ello.

2022-01-31 17:42 UTC, sorozcov commented on tests/test_historial_partidos.py
> +    with pytest.raises(FileNotFoundError):
Assertpy trabaja con un fluent API que permite el desarrollo rápido de tests con funciones muy sencillas que simplifican el trabajo en los tests. Me había equivocado y si tiene una forma de verificar excepciones al llamar una función con .raise().

2022-02-02 11:47 UTC, sorozcov commented on docs/objetivo4.md
> +- Se reduce código boilerplate y se centra en funciones legibles y sencillas que testean las funcionalidades.
Se ha contestado esto y modificado a una documentación correcta de este objetivo.

2022-02-02 11:48 UTC, sorozcov commented on README.md
> +La librería de tests que se está utilizando es pytest.
Se ha modificado el archivo correctamente, justo como lo mencionas seleccionando pytest (framework) como nuestro test runner.

2022-02-02 16:09 UTC, sorozcov commented on code/apuesta.py
>  class Apuesta:
Se han planteado los issues correspondientes #23 y #25

2022-02-02 16:11 UTC, sorozcov commented on tests/test_prediccion.py
> +import numpy as np
Se ha quitado numpy que no se usaba.

2022-02-02 16:14 UTC, sorozcov commented on code/historial_partidos.py
> +                raise EquipoSolicitadoNoEstaEnPrimeraDivision("Equipo solicitado no se encuentra en primera división.")
Se ha corregido eliminando dicha Exception que era innecesaria primeramente al tener una forma más efectiva de comprobarlo.