Objetivo 5
sorozcov/proyecto-iv-ugr pull request #29
Opened 2022-01-05 18:20 UTC by sorozcov

* [ ]  ¿Se han seguido las buenas prácticas en las órdenes que construyen
   la imagen? ¿Especialmente las relativas a usuarios no privilegiados y demás?
* [ ]  ¿La imagen incluye sólo y exclusivamente la infraestructura
   necesaria para pasar los tests?
* [ ]  ¿Se han documentado y enlazado los commits a las imágenes que se
   han testeado?
* [ ]  ¿Está establecido correctamente como `WORKDIR` el que se va a usar en los
   tests que se van a lanzar?
* [ ]  ¿Se han establecido claramente los criterios de búsqueda y de aceptación de
   la imagen base?
* [ ] ¿Tienes claro cuales son las condiciones en las que tiene que actualizarse
la imagen en DockerHub y has configurado el workflow de acuerdo con ello?

Se ha trabajo en los issues.
- #26 
- #27 
- #28

2022-01-05 19:36 UTC, JJ commented
⛹ Revisores → @Slowmybrosh @Balrrach @jesusmarzor

2022-01-08 18:47 UTC, JJ requested changes
Lo siento, no pasa. No es un contenedor para correr los tests infinitamente dentro del mismo (¿por qué se querría hacer tal cosa?), sino con lo necesario para ejecutar los tests y que *monte* los fuentes para hacer los mismos.

2022-01-08 18:47 UTC, JJ commented on Dockerfile
> +
No has incluido el workdir correcto.

2022-01-08 18:47 UTC, JJ commented on Dockerfile
> +COPY pyproject.toml poetry.lock tasks.py tests code ./
El contenedor *no* puede incluir el código que se supone que va a testear.

2022-01-08 23:47 UTC, sorozcov commented on Dockerfile
> +COPY pyproject.toml poetry.lock tasks.py tests code ./
Hola @JJ, una pregunta genuina si pudieses ayudarme, había incluido esto porque de lo contrario no lograba que corriera ningún test del proyecto al hacer el run de docker. ¿Podrías ayudarme a comprender mi error en este caso?

Gracias.

2022-01-08 23:47 UTC, sorozcov commented on Dockerfile
> +
Si, me he dado cuenta que era sobre /app/test. Aún estaba esperando si alguien de los revisores me ayudaba pero no sucedió.

2022-01-09 00:16 UTC, sorozcov commented on Dockerfile
> +COPY pyproject.toml poetry.lock tasks.py tests code ./
Viendo el trabajo de otros compañeros, más o menos veo que no corren ningún test. Por lo tanto, entiendo entonces que mi error es que únicamente se estaba montando lo necesario de infraestructura como mencionas y que lo único que me faltó para pasar este objetivo fue el no copiar el código ni los tests en mi contenedor y también utilizar el directorio correcto?

2022-01-09 04:02 UTC, sorozcov commented on Dockerfile
> +COPY pyproject.toml poetry.lock tasks.py tests code ./
Ya lo he comprendido ahora trabajando en el objetivo 6. Lo he corregido y quisiera saber, ¿Si puedo realizar el pull request del objetivo 6 que ha salido inicialmente de la rama del objetivo 5?

2022-01-09 07:51 UTC, JJ commented on Dockerfile
> +COPY pyproject.toml poetry.lock tasks.py tests code ./
simplemente no estás entendiendo lo que se pide en el [guión](https://jj.github.io/IV/documentos/proyecto/4.Tests). Repásalo, así como los errores frecuentes en las sesiones posteriores.
Puedes realizar los PRs que desees. Si consideras que no te a va a dar tiempo para la convocatoria ordinaria (que acaba en tres días) puedes empezar a enviar todos los que no hayas superado para la convocatoria extraordinaria.

2022-01-09 12:29 UTC, sorozcov commented on Dockerfile
> +COPY pyproject.toml poetry.lock tasks.py tests code ./
Okay gracias.

2022-01-09 12:29 UTC, merged

2022-01-27 14:57 UTC, sorozcov commented on Dockerfile
> +COPY pyproject.toml poetry.lock tasks.py tests code ./
Se ha corregido esta parte dónde se copiaba incorrectamente el código en el contenedor y por lo tanto, no era lo que se solicitaba. https://github.com/sorozcov/proyecto-iv-ugr/pull/36

2022-01-27 14:57 UTC, sorozcov commented on Dockerfile
> +
Se ha corregido el directorio correcto trabajando sobre /app/test https://github.com/sorozcov/proyecto-iv-ugr/pull/36