Objetivo 6 provisional
sorozcov/proyecto-iv-ugr pull request #34
Opened 2022-01-09 12:32 UTC by sorozcov

* [ ]  ¿Se han configurado varios sistemas de integración continua?
* [ ]  ¿Se ha configurado correctamente el *Checks API* en los sistemas en los que
   sea necesario para que aparezca correctamente en GitHub (y se pueda comprobar
   desde los tests)?
* [ ]  ¿Uno de los sistemas configurados permite comprobar cuales son las versiones
   del lenguaje con las que funciona correctamente nuestra aplicación?
* [ ]  ¿Se escogen de forma adecuada las versiones del lenguaje que se testean,
   tanto en el sistema de CI como en el contenedor Docker?

Se ha trabajado en los issues:

- #30 
- #31 
- #32 
- #33

2022-01-09 16:09 UTC, JJ commented
⛹ Revisores → @Olasergiolas @JAntonioVR @amerigal

2022-01-10 00:13 UTC, JAntonioVR requested changes
Muy buenas Silvio, acabo de terminar de revisar tu PR. En general está completo, destaco la documentación y la propuesta de alternativas de la documentación. Sin embargo te dejo algunas propuestas abajo y aquí te voy a poner también una duda que tengo.

En tu Dockerfile construyes un contenedor que utiliza la versión 3.9 de python, pero no veo que se construya en ningún momento un contenedor que utilice la versión 3.8 y 3.10 que después se testean. Yo recomiendo parametrizar la construcción del Docker e incluir actions de construcción y subida a dockerhub de las tres versiones que vas a testear. Así además tienes bien pillado cualquier fallo relacionado con tema de versiones cada vez que se ejecuta la CI.

Si no estás de acuerdo o piensas que no llevo razón estaré encantado de escuchar tus argumentos. Espero haberte sido de ayuda, mucha suerte!

2022-01-10 00:13 UTC, JAntonioVR commented on docs/objetivo6.md
> +Como segunda herramienta, se ha escogido Travis CI. Travis CI es también muy parecido a CircleCI y permite una configuración fácil de la integración continua. Esta herramienta será utilizada junto co
Simplemente por tema de estructura, mejor escribir que Travis cumple los requisitos y blabla y por eso se ha elegido como segunda herramienta. Dicho de otra forma, los criterios y la búsqueda del panorama deben ir antes de la decisión final

2022-01-10 14:52 UTC, sorozcov commented on README.md
> +- [Objetivo 6: Integración Continua ](https://github.com/sorozcov/proyecto-iv-ugr/tree/objetivo-5/docs/objetivo6.md)
Gracias por la sugerencia no me había percatado que esto era posible.

2022-01-10 14:54 UTC, sorozcov commented on .circleci/config.yml
> +              version: ["3.8","3.9","3.10"]
Lo había colocado en la descripción del commit pero lo agregaré a la documentación.

2022-01-10 15:00 UTC, sorozcov commented on docs/objetivo6.md
> +- Automatizar los tests cada vez que se lleve a cabo un pull request en el proyecto
Tienes razón, ahora arreglaré dicha documentación.

2022-01-10 15:03 UTC, sorozcov commented on docs/objetivo6.md
> +Como segunda herramienta, se ha escogido Travis CI. Travis CI es también muy parecido a CircleCI y permite una configuración fácil de la integración continua. Esta herramienta será utilizada junto co
Lo he arreglado en la documentación.

2022-01-10 15:10 UTC, sorozcov commented
> Muy buenas Silvio, acabo de terminar de revisar tu PR. En general está completo, destaco la documentación y la propuesta de alternativas de la documentación. Sin embargo te dejo algunas propuestas abajo y aquí te voy a poner también una duda que tengo.
> 
> En tu Dockerfile construyes un contenedor que utiliza la versión 3.9 de python, pero no veo que se construya en ningún momento un contenedor que utilice la versión 3.8 y 3.10 que después se testean. Yo recomiendo parametrizar la construcción del Docker e incluir actions de construcción y subida a dockerhub de las tres versiones que vas a testear. Así además tienes bien pillado cualquier fallo relacionado con tema de versiones cada vez que se ejecuta la CI.
> 
> Si no estás de acuerdo o piensas que no llevo razón estaré encantado de escuchar tus argumentos. Espero haberte sido de ayuda, mucha suerte!

Gracias por la ayuda. He realizado los cambios que me has sugerido. Con la sugerencia de Docker también me parece interesante aunque creo que si ya tiene la infraestructura en CircleCI, me cuestionó si es necesario realizar la misma infraestructura en el contenedor de Docker. Es decir, ¿Tener la misma infraestuctura 2 veces esperando un fallo en CI?. Quedo a la espera de tus comentarios y de los demás, para ver si se realiza este cambio. Gracias.

2022-01-11 16:06 UTC, sorozcov commented
Listo para revision @JJ ya que no han habido más revisiones.

2022-01-12 09:11 UTC, JAntonioVR requested changes
Has solucionado los fallos de la documentación, pero aún hay un detalle que me rechina respecto al contenedor que utilizas.

2022-01-12 09:11 UTC, JAntonioVR commented on .circleci/config.yml
> +      - image: circleci/python:<< parameters.version >>
Dices entonces que lo que utilizas es el contenedor propio de CircleCI, pero entonces lo que veo es que no es necesario cada vez que hagas un push ponerte a instalar dependencias cuando tienes subido a dockerhub tu contenedor con todas sus dependencias instaladas, que es precisamente el objetivo.

Y cualquier decisión que tomes finalmente respecto a este tema deberías dejarla documentada para que quede clara.

2022-01-12 10:33 UTC, sorozcov commented on .circleci/config.yml
> +      - image: circleci/python:<< parameters.version >>
Gracias, he seguido tu recomendación de actualizar el Dockerfile para que pueda testear diferentes versiones y luego lo he cambiado en CircleCI ya que tienes razón en que precisamente este contenedor se ha creado con la infraestructura mínima necesaria para realizar el testing del proyecto. Si puedes revisarlo rápidamente ante de solicitar revisión.

2022-01-12 10:54 UTC, JAntonioVR approved these changes
Así me gusta más :smile: 
Por mi parte está correcto, buen trabajo!

2022-01-12 13:19 UTC, sorozcov commented
Listo para revisión @JJ

2022-01-12 22:37 UTC, sorozcov commented
> Listo para revisión @JJ

Hola @JJ, solo con la consulta que esto estaba listo para revisión antes que terminara la convocatoria ordinaria.

2022-01-14 10:03 UTC, JJ requested changes
Necesitas entender mejor los conceptos relativos a este objetivo, y establecer bien los criterios de elección, que como siempre es algo fundamental. Estás testeando lo mismo en los dos sitios de test (versión 3.9) y además de la misma forma (con contenedores Docker). No se trata de eso. Por favor, revísalo para la convocatoria extraordinaria si lo deseas.

2022-01-14 10:03 UTC, JJ commented on docs/objetivo6.md
> +	- Necesita un servidor dedicado lo cual si requiere costos adicionales.
Por lo que ponerlo aquí solo añade ruido. En clase os dije que pusiérais unos prerrequisitos o criterios de búsqueda para decidir qué sistemas ibais a examinar para tomar una decisión. ¿Ibais a poner vosotros un ordenador para hacer los tests? No. Entonces, ¿por qué lo pones aquí?

2022-01-14 10:23 UTC, sorozcov commented
> 

Okay, gracias @JJ. Solo para aclarar que la versión 3.9 solo se testea en Travis y no en Circle CI. Sobre la convocatoria extraordinaria cómo no he superado otros objetivos, se trabaja sobre el mismo branch o se saca un nuevo branch del main ya que tiene actualizaciones?

2022-01-14 10:34 UTC, JJ commented
> > 
> 
> Okay, gracias @JJ. Solo para aclarar que la versión 3.9 solo se testea en Travis y no en Circle CI. Sobre la convocatoria extraordinaria cómo no he superado otros objetivos, se trabaja sobre el mismo branch o se saca un nuevo branch del main ya que tiene actualizaciones?

A tu elección, pero tienes que enviarlo de nuevo para que pase los tests e indicarlo de la forma que se ha hecho en el documento aparte. Para mi quizás es más cómodo que sea la misma rama, así veo los comentarios que se han hecho antes y cómo se han solucionado los problemas, pero es cosa tuya.

2022-01-14 10:38 UTC, sorozcov commented
> > Okay, gracias @JJ. Solo para aclarar que la versión 3.9 solo se testea en Travis y no en Circle CI. Sobre la convocatoria extraordinaria cómo no he superado otros objetivos, se trabaja sobre el mismo branch o se saca un nuevo branch del main ya que tiene actualizaciones?
> 
> A tu elección, pero tienes que enviarlo de nuevo para que pase los tests e indicarlo de la forma que se ha hecho en el documento aparte. Para mi quizás es más cómodo que sea la misma rama, así veo los comentarios que se han hecho antes y cómo se han solucionado los problemas, pero es cosa tuya.

Claro, entonces podría hacer los pull requests a la rama del objetivo anterior que era como se encontraba el main en ese momento? O crees que es mejor hacer un rebase de los branches con el main?

2022-01-14 10:46 UTC, JJ commented
> > > Okay, gracias @JJ. Solo para aclarar que la versión 3.9 solo se testea en Travis y no en Circle CI. Sobre la convocatoria extraordinaria cómo no he superado otros objetivos, se trabaja sobre el mismo branch o se saca un nuevo branch del main ya que tiene actualizaciones?
> > 
> > 
> > A tu elección, pero tienes que enviarlo de nuevo para que pase los tests e indicarlo de la forma que se ha hecho en el documento aparte. Para mi quizás es más cómodo que sea la misma rama, así veo los comentarios que se han hecho antes y cómo se han solucionado los problemas, pero es cosa tuya.
> 
> Claro, entonces podría hacer los pull requests a la rama del objetivo anterior que era como se encontraba el main en ese momento? O crees que es mejor hacer un rebase de los branches con el main?

También es cosa tuya. Ten en cuenta que si vas a cambiar la rama anterior, y haces cambios en ella incompatibles con esta rama, puedes tener problemas. Yo extraería de la otra rama lo necesario, creo que así es como lo han hecho casi todo slos compañeros.

2022-02-02 17:08 UTC, sorozcov commented on docs/objetivo6.md
> +- Que tenga una compatibilidad alta de integración con GITHUB.
Sisi, tienes razón no es un criterio, sino también lo que necesita y brinda cualquier sistema de IC.

2022-02-02 17:08 UTC, sorozcov commented on docs/objetivo6.md
> +- Que luego de cada push en un branch o pull request al proyecto se pueda automatizar el testing del proyecto.
Sisi, tienes razón no es un criterio, sino más bien la base de cualquier sistema de IC.

2022-02-02 17:09 UTC, sorozcov commented on docs/objetivo6.md
> +- Testear el proyecto en varias versiones del lenguaje lenguajes
Corregido.

2022-02-02 17:11 UTC, sorozcov commented on docs/objetivo6.md
> +	- Necesita un servidor dedicado lo cual si requiere costos adicionales.
Tienes razón. me había parecido únicamente interesante investigarla por ser de los primeros IC que han sido altamente utilizados por la comunidad. Lo he quitado porque hace ruido como bien dices.

2022-02-02 17:11 UTC, sorozcov commented on docs/objetivo6.md
> +	- Tiene alta customización
Se ha quitado Jenkins que no tiene sentido al hacer ruido como mencionaste.

2022-02-02 17:12 UTC, sorozcov commented on .circleci/config.yml
> +      - image: sorozcov/proyecto-iv-ugr:<< parameters.version >>
Esto se ha corregido para cambiarse en los paths correspondientes en cualquier rama. También trabajado en la corrección del objetivo 5. Tenía el contenido real del repositorio porque había hecho los push manuales.

2022-02-02 17:13 UTC, sorozcov commented on .github/workflows/docker-image.yml
>      branches: [ main ]
Esto se ha corregido para cambiarse en los paths correspondientes en cualquier rama. También trabajado en la corrección del objetivo 5. Tenía el contenido real del repositorio porque había hecho los push manuales.

2022-02-02 17:13 UTC, sorozcov commented on .circleci/config.yml
> +              version: ["3.8","3.10"]
En la documentación ya estaban las versiones seleccionadas junto con su respectiva justificación.

2022-02-02 17:41 UTC, sorozcov commented on docs/objetivo6.md
> +	- Tiene un mayor soporte de otros lenguajes de programación que CircleCI no tiene.
Se han actualizado los criterios.

2022-02-03 13:44 UTC, sorozcov commented
* [ ] ¿Se ha evitado Circle CI, porque a estas alturas ya lo ha usado todo el
mundo?
* [ ] ¿Se han establecido criterios *a priori* para elegir el sistema de
integración continua más conveniente y se han calificado los sistemas que
cumplan esos requisitos según esos criterios?
* [ ] ¿Se han examinado varios sistemas de integración continua?
* [ ] ¿Se han configurado varios sistemas de integración continua?
* [ ] ¿Se ha configurado correctamente el *Checks API* en los sistemas en los que
   sea necesario para que aparezca correctamente en GitHub (y se pueda comprobar
   desde los tests)?
* [ ] ¿Uno de los sistemas configurados permite comprobar cuales son las versiones
   dellenguaje con las que funciona correctamente nuestra aplicación?
* [ ] ¿Se escogen de forma adecuada las versiones del lenguaje que se testean,
   tanto en el sistema de CI como en el contenedor Docker?
* [ ] ¿Se han justificado correctamente las versiones del lenguaje que se están
testeando y se ha comprobado que no se comprueban varias veces lo mismo (la
misma versión en CI y en el contenedor Docker en otro sistema CI?

2022-02-09 13:02 UTC, merged