Objetivo 1
sorozcov/proyecto-iv-ugr pull request #7
Opened 2021-10-20 20:58 UTC by sorozcov

2021-11-02 14:33 UTC, sorozcov commented
Listo para revisión. El algoritmo escogido a desarrollar es predicción de resultados a través de un arbol de decisión que tome en cuenta el historial de partidos reciente de ambos equipos tanto entre ellos como con los demás equipos de la liga. En el historial se tomarán atributos como la posesión, tiros de esquina, cantidad de faltas, lugar en la tabla y por supuesto, cantidad de goles en los partidos pasados. Esto se específica en el Milestone 2.

2021-11-02 14:35 UTC, gomares commented
@JJ listo para revisión

2021-11-05 09:07 UTC, JJ requested changes
Aparte de los errores indicados en #5 y #6 , los milestones no son productos mínimamente viables y están ordenados siguiendo más el flujo de datos que una verdadera planificación de la creación de un proyecto.

2021-11-05 09:08 UTC, JJ commented
> @JJ listo para revisión

¿Qué está listo para revisión? ¿Entiendes lo que tienes que hacer para el objetivo 2?

2021-11-05 23:18 UTC, sorozcov commented
@JJ Cambios listos para revisión.

2021-11-06 09:10 UTC, JJ requested changes
Por favor, revisa de nuevo [el guión de este objetivo](http://jj.github.io/IV/documentos/proyecto/1.Infraestructura).
1. No hay ningún HU asignado al primer milestone. Mira [la lista de comprobación sobre milestones](http://jj.github.io/IV/documentos/proyecto/1.Infraestructura#listas-de-comprobaci%C3%B3n) para ver qué otras condiciones no cumplen estos milestones. Por ejemplo, el milestone 1 no es *mínimo*, porque incluye funcionalidad
2. El desarrollo no se construye siguiendo el flujo de datos. Si hay que leer datos primero,no necesariamente tienes que hacer primero la clase que lea los datos. 
3. Los PMVs tienen que expresar claramente qué producto hay que entregar. "Clases básicas" no es una descripción adecuada. En [ese hito](https://github.com/sorozcov/proyecto-iv-ugr/milestone/2) estás tomando decisiones sobre cuál es la clase más importante, que corresponderían también al segundo objetivo, siguiendo el diseño dirigido por dominio.

2021-11-09 16:26 UTC, sorozcov commented
1. He quitado el Milestone 1, que inicialmente  se llamaba Desarrollo de Clases Base porque realmente he entendido que no es un PMV porque no se puede entregar un producto a partir de ello ni realizar ninguna iteración. Por lo tanto, he decido que el desarrollo del algoritmo de predicción sea el milestone 1 que es el primer producto mínimamente viable a entregar, y la creación de clases para lectura de datos serán issues pertenecientes a este milestone.  Queda asignado el HU1 a M1.

2021-11-09 16:27 UTC, sorozcov commented
Listo para revisión @JJ

2021-11-09 16:28 UTC, JJ commented
¿Estás seguro? ¿Sin ningún cambio en el repositorio?

2021-11-09 16:30 UTC, sorozcov commented
Hice un commit y reconfigure en issues y milestones.

2021-11-09 19:39 UTC, JJ commented
> Las HUs apenas se diferencian. Los milestones son inespecíficos y no se refieren a un producto determinado, sino a "clases básicas". Si no dices qué tienen que tener las clases básicas para aceptar este hito, no son aceptables como productos mínimamente viables. El resto de los milestones son acciones del usuario, más que productos mínimamente viables. Por favor, revisa este concepto que es el más importante en este objetivo.

Los milestones siguen sin ser productos mínimamente viables. El M1 ni siquiera es mínimo (segurametne habrá que hacer muchas cosas, PMVs internos, antes de llegar a él) y ninguno de los dos dice qué producto mínimamente viable va a producirse. Además, el número es inferior al obligatorio en este hito, que es de 3 (y por tanto fallaría en el siguiente objetivo). Te agradecería que hicieras todos los cambios solicitados, porque sin ellos no es posible superar el objetivo.

2021-11-11 09:24 UTC, sorozcov commented
Listo para revisión @JJ

2021-11-11 19:35 UTC, JJ approved these changes
Por favor, pon en práctica lo dicho sobre los mensajes de commit de ahora en adelante.

2021-11-12 11:47 UTC, merged